sei-protocol/sei-db

benchmark/dbbackend/benchmark.go
ss/sqlite.go

- Adds sqlite as backend for benchmark
- Changes comments for fns that were previously rocksdb-specific
- Tested on local, verifying on node

[SeiDB] Add Sqlite Benchmark Setup

---

sc/memiavl/db/tree.go
sc/memiavl/store/rootmulti/store.go
ss/setup.go

We need to add a write lock for the tree cache access to avoid panics for concurrent map read.
Tested in atlantic-2 testnet

[Bug] Fix concurrent map read 

---

ss/sqlite/db.go

- Previously the sqlite `New` assumed the full path to dataDir already existed
- Adds a `os.MkdirAll` to create all the intermediate paths
- Testing on node

[SeiDB] Update Sqlite Dir

---

config/config.go
config/toml.go
ss/pebbledb/db.go
ss/rocksdb/db.go
ss/setup.go
ss/sqlite/db.go
ss/store/import.go
ss/store/multistore.go
ss/types/types.go

- Parallelizes import
- Spins up `numWorkers` goroutines to import 
- NOTE: Did not add to sqlite since we use tx's 
- Tested on local machine parallel import, testing on node

[SeiDB] Parallelize Import

---

sc/memiavl/db/import.go
sc/memiavl/db/snapshot.go
sc/memiavl/db/snapshot_test.go

Context:
After investigating the memIAVL import performance, we find that it is spending lot of extra time waiting on the channel. Adding some buffer size for the channel will greatly improve the performance of import.
Tested on atlantic-2

Perf: Improve memIAVL import speed by 2X

---

ss/pebbledb/db.go

- Clones the value of the iterator. Ran into issues on a node when running pruning where after some time the value was incorrect
- Verified this on a node
- Testing on local again

[SeiDB] PebbleDB Prune Clone Iterator value

---

ss/pebbledb/comparator.go
ss/pebbledb/iterator.go
ss/test/storage_test_suite.go

- Fix for PebbleDB Iterator issue
- Previously, the mvcc iterator would loop indefinitely when it reached a key that was greater than the iterator version specified and go back to a previous key
- Catch the scenario where iterator moves back to previous key and move it forward to avoid a loop
- Tested and repro'd error on node 
Before fix: 
After fix:

[SeiDB] Fix PebbleDB Iterator Issue

---

ss/pebbledb/db.go

- Addresses issue where during pruning OOM occurs since the batch's are not freed properly
- use batch.Reset instead of batch.Close
- Testing on node
- Looking into how to add unit tests

Prune Batch Reset

---

sc/memiavl/benchmark_test.go
sc/memiavl/db.go
sc/memiavl/db_test.go
sc/memiavl/import.go
sc/memiavl/multitree.go
sc/memiavl/proof_test.go
sc/memiavl/snapshot.go
sc/memiavl/snapshot_test.go
sc/memiavl/tree_test.go
ss/pebbledb/db.go

During shutdown process,  currently when MemIAVL is taking a snapshot, it will throw panic with segmentation fault. 
This PR mostly cherry pick the fix from https://github.com/crypto-org-chain/cronos/pull/1292.
Tested on a seidb node with manual restart

Improve memiavl graceful shutdown

---

ss/pebbledb/iterator.go
ss/test/storage_test_suite.go

- Separates out logic for forward and reverse iteration
- During iterator initialization, makes sure to call `Next` if not on a key which is valid (version <= requested version)
- For Forward and Reverse case, adds a check at end to verify if the key has a version <= requested version, if not, will recursively call `Next` again. Previous logic did not guarantee in such edge cases that a Next call would move the iterator either to a key which is valid or exhaust it
- Unit tests added
- Testing on node + integration tests

PebbleDB Iterator Fix

---

ss/pebbledb/db.go
ss/rocksdb/db.go
ss/sqlite/db.go
ss/test/storage_test_suite.go
ss/types/store.go

- Expose `GetEarliestVersion` in State Store
- NOTE: Earliest version is only updating after a successful prune, not before or during
- Unit tests for earliest version

[SeiDB] State Store Expose `GetEarliestVersion`

---

sc/memiavl/db.go
sc/memiavl/layout_native.go
sc/memiavl/multitree.go
sc/memiavl/tree.go
ss/store.go

This PR address a few minor issues from audit:
- The replay [here](https://github.com/sei-protocol/sei-db/blob/main/ss/store.go#L82) should probably start from targetStartOffset + 1 instead of targetStartOffset, since ssLatestVersion is already in the db.
- I think deriving the group context from argument ctx instead of Background.Context makes more sense [here](https://github.com/sei-protocol/sei-db/blob/main/sc/memiavl/multitree.go#L365). Additionally, don't we want to use the context derived from wp.GroupContext for WriteSnapshot?
- It seems like we would like to allow version up to Uint32.Max, but strconv.ParseInt [here](https://github.com/sei-protocol/sei-db/blob/main/sc/memiavl/db.go#L734) can only handle up to Int32.Max for bitSize = 32. Using strconv.ParseUint would be a better …

Various fixes from audit

---

config/config.go
config/toml.go
sc/memiavl/benchmark_test.go
sc/memiavl/multitree.go
sc/memiavl/tree.go

**Problem:**
We are seeing some unsafe/bug regards to this cache node that could cause a node to crash:
**Solution:**
The simple solution is to completely remove this LRU cache. With a recent benchmark we notice there isn't any improvement when we enable/disable this cache because mmap page cache already serves as a similar cache layer. Removing this would actually save some cpu usage. 
We can also rely on the inter-block-cache in cosmos layer for a real application cache.

Bug Fix: Remove LRU cache on top of memiavl

---

sc/memiavl/db.go
sc/memiavl/db_test.go
sc/memiavl/multitree.go
sc/memiavl/tree.go

**Problem:**
In EVM, serving EVM RPC endpoints will have to query and access the latest state or historical state, when accessing latest state from MemIAVL, there's a race condition where the key we are trying to access doesn't exist because in the background, we have already switched to a difference snapshot after snapshot rewrite completes. Here's how it could happen:
1. Goroutine A: get a Tree pointer, preparing to call tree.Get
2. Goroutine B: reload snapshot and switched to a new tree, closed old tree
3. Goroutine A: Still use the old tree pointer to call get, got segmentation fault
And here's the error when this race condition is triggered:
**Solution:**
This PR address the issue by doing an internal replacement, instead of closing the old tree and create a new tree, we replace all …

[SeiDB] Fix MemIAVL Race Condition during snapshot reload

---

sc/memiavl/db.go
sc/memiavl/filelock.go
sc/memiavl/snapshot.go

Fix issues found by audit
- CleanupHandles should be called correctly
- The fileLock is never destroyed [here](https://github.com/sei-protocol/sei-db/blob/c74058fc824abcf3ba4463ca5d37ab4477759e7d/sc/memiavl/db.go#L615), leading to an unclosed file
Existing unit test should cover it

[SeiDB] Fix various issues from audit

---

sc/store.go

LoadVersion should open DB with read only when createNew is true, otherwise it will hit filelock and fail to open the DB

LoadVersion should open DB with read only

---

ss/pebbledb/iterator.go
ss/test/storage_test_suite.go
ss/test/utils.go

Currently, if the starting key is tombstoned, iterator will still return a valid value with TOMBSTONE, which is incorrect.
The correct logic should be to check whether the first value is a TOMBSTONE flag, if so, we should call nextForward or nextReverse to move onto the next valid key, which will correctly handle and filter out all TOMBSTONE values.
Added unit test to cover this edge case

Fix edge case for iterating over tombstoned value

---

tools/cmd/seidb/main.go
tools/cmd/seidb/operations/dump_db.go
tools/cmd/seidb/operations/module.go
tools/cmd/seidb/operations/prune.go
tools/cmd/seidb/operations/state_size.go

This PR add a tool to dump a module size by prefix and also tells us total size.
Example output:
> root@ip-172-31-35-60:/home/ubuntu/sei-db/tools# seidb state-size -d ~/.sei/data/committer.db -m evm --height 82939158
> Calculating for module: evm 
> Module evm total numKeys:4446893, total keySize:103482401, total valueSize:1461642400, totalSize: 1565124801 
> Module evm prefix breakdown: {
>   "01": 1848008,
>   "02": 1847960,
>   "03": 3970464,
>   "07": 22294760,
>   "08": 83968,
>   "09": 20992,
>   "0A": 169064,
>   "0B": 1306833685,
>   "0D": 50665984,
>   "0E": 73859936,
>   "15": 12262,
>   "16": 16,
>   "17": 35301
> }

Add command line tool to dump chain state size

---

config/config.go
config/toml.go
ss/pebbledb/db.go
ss/pebbledb/db_test.go
ss/test/storage_test_suite.go

- Introduce new state store config `KeepLastVersion` which dictates whether pruning should keep the latest version of a key or delete it
- Added unit tests
- Verifying on node

KeepLastVersion config for pruning

---

ss/pebbledb/batch.go
ss/pebbledb/db.go
ss/test/storage_test_suite.go
ss/types/store.go

- For archive node migration, adds `RawImport` and `RawBatch` which allows importing in kv entries in any order of version
- Added unit tests for both `RawImport` and `Import`
- Tested on node (re routed `Import` to use `RawImport`), verifying on new cluster

Add Raw Import and Raw Batch for Writing to SS in any order of version

---

tools/cmd/seidb/main.go
tools/cmd/seidb/operations/replay_changelog.go

This PR introduce a new seidb command to replay changelog, at the same time we can choose to reapply the changelog to DB if we want to recover any missing data
Tested on snapshotter node

Add a tool to replay changelog and repair missing entry in DB

---

ss/pebbledb/db.go
ss/rocksdb/db.go
ss/rocksdb_init.go
ss/sqlite/db.go
ss/sqlite_init.go
ss/store.go
ss/store_test.go

The changelog path could be wrong if someone overwrite the DB directory, which could lead to failure of recovery during ss restart.
Tested on RPC node and make sure receipts are recovered everytime after seid crash

Fix changelog recover failure due to wrong path

---

tools/cmd/seidb/operations/replay_changelog.go

This PR add default offset to the replay tool so that it will default to run from index 1 to the latest changelog index.

Enhance replay chagnelog tool to replay till the end

---

ss/pebbledb/db.go

init app earliest version correctly after state sync to avoid app earliest version < block earliest version

fix: init app earliest version correctly after state sync

---

tools/dbbackend/benchmark.go
tools/utils/utils.go

- Adds upper limit on number of goroutines spun up to read kv files
- Verifying on node

Add upper limit on file parsing goroutines

---

go.mod
go.sum
ss/pebbledb/db.go
ss/types/store.go

- Adds setting latest migrated key and module and restarting from there
- Verifying on node migration

Archive migration online

---

tools/cmd/seidb/operations/state_size.go

feat: state size print top 20 contracts by total size

---

tools/cmd/seidb/operations/state_size.go

fix: sort evm state by total size

---

tools/cmd/seidb/operations/state_size.go

This PR also dump number of keys per prefix for state dump tool.

Add num of keys for state dump

---

ss/pebbledb/db.go
ss/test/storage_test_suite.go

- Fix to bug in `ReverseIterate` when upper bound is `nil` and seeks to a key which is not in the current store and immediately invalidates
- Update upper bound, seek to latest possible key in a store 
- Added unit test, verifying on node

Add Upper Bound ReverseIterator

---

config/config.go
config/toml.go
sc/memiavl/export.go
sc/memiavl/opts.go
sc/memiavl/snapshot_test.go
sc/store.go

This PR added a new config to only allow state sync export creation to happen after we have a memiavl snapshot for that height

Add config for to OnlyAllowExportOnSnapshotVersion
