sc/memiavl/db/tree.go
sc/memiavl/store/rootmulti/store.go

- Add locks to prevent concurrent map modifications around stores map
- Add locks to protect cache concurrent access
Locally tested in docker chain

Add mutex for stores

---

ss/sqlite/db.go

- Due to refactor in this PR: https://github.com/sei-protocol/sei-db/pull/16 we need to update an import path for state store
- Ran and verified

[SeiDb] Update Sqlite Backend Import

---

ss/pebbledb/db.go

- Adds ZSTD compression to each pebble layer
- Testing on node and verifying

[SeiDB] Add PebbleDB Compression

---

ss/rocksdb.go

Fix a typo for rocksdb backend

Fix backend name for rocksdb

---

ss/pebbledb/db.go
ss/pebbledb/iterator.go

- Adds PebbleDB Reverse Iteration
- Testing on node

[SeiDB] PebbleDB Reverse Iteration

---

common/utils/bytes_test.go
config/config.go
config/toml.go
go.mod
go.sum
ss/pruning/manager.go
ss/setup.go

Changes:
- Adding a pruning manager for state store
- Add new pruning configs for state store 
Pruning manager will start a goroutine to trigger the state store prune every interval plus a random delay

Feat: Add pruning manager for state store

---

ss/pebbledb/db.go

- Remove Tombstone check in PebbleDB which checks if tombstone version is greater than targetVersion
- Tested and verified on node and locally

[SeiDB] Remove Get Tombstone Check

---

ss/pebbledb/db.go

- Iterate over versioned keys and deletes in batches
- Deletes all keys <= prune version
- Testing on local and on node

[SeiDB] PebbleDB Pruning

---

ss/pebbledb/db.go

- Avoids earliest key metadata during iteration
- Tested fully on node and verified

[SeiDB] Avoid Metadata During Iteration

---

ss/pebbledb/db.go
ss/pebbledb/db_test.go
ss/pebbledb/iterator.go
ss/rocksdb/db_test.go
ss/sqlite/db_test.go
ss/storage_test_suite.go
ss/test/storage_test_suite.go
ss/test/utils.go

- Part 1 of State Store Unit Tests
- Sets of Storage Suite Test Framework + Initial tests (apply changeset, prune etc)
- NOTE: Also adds to pebble iterator immediate return + invalid iterator if requesting version earlier than prune height
- Verified test locally

[SeiDB] Pt 1: State Store Unit Tests

---

config/config.go
config/toml.go
sc/setup.go
ss/pruning/manager.go
ss/setup.go

Changes:
- Add a new config for SS store so that we can override the directory for ss store
- Refactor a few config names 
Tested on local docker chain

[SeiDB] Add configuration to override ss database directory

---

ss/test/storage_test_suite.go
ss/test/utils.go

- Adds unit tests for parallel delete and iteration, parallel write and delete, parallel iteration and pruning and parallel iterations over multiple versions
- Refactors DBApplyChangeset and changes more fn's to use that utility
- Tested and verified unit tests

[SeiDB] Part 3 State Store Unit Tests

---

sc/memiavl/db.go
ss/pruning/manager.go

Need to add fmt.sprintf, otherwise it will throw conversion error

Fix pruning  manager logs

---

config/config.go
config/toml.go

Update the config descriptions to make it more accurate

Update config description and defaults

---

README.md
sc/memiavl/README.md
sc/store.go

This PR include 3 changes:
1. Add ReadMe for SeiDB
2. Add ReadMe for MemIAVL
3. Fix LoadVersion bug where it should open DB with readOnly mode

Add readme for SeiDB

---

sc/memiavl/db.go

This PR fix the metadata dir issue for getLatestVersion, which will be used during store upgrades.

Fix metadata file path for upgrade

---

config/toml.go

We should not let users to customize this new config KeepLastVersion since it should always be true

Remove new config from app.toml

---

tools/cmd/seidb/operations/state_size.go

We have value size breakdown, this PR add key size breakdown by prefix.

Add key and value size breakdown

---

sc/memiavl/db.go
sc/store.go
sc/types/store.go

SC GetEarliestVersion

---

.github/workflows/unit_tests.yml
Makefile
codecov.yml

[SEI-9787] require 70% patch coverage
